---
- name: Install macOS Software
  hosts: localhost
  connection: local
  vars:
    brew_cask_packages:
      - 'docker'
      - 'firefox'
      - 'google-chrome'
      - 'intellij-idea-ce'
      - 'pycharm-ce'
      - 'skype'
      - 'vagrant'
      - 'virtualbox'
      - 'virtualbox-extension-pack'
      - 'visual-studio-code'
      - 'zoomus' 
    brew_packages:
      - 'autoconf'
      - 'bash-completion'
      - 'docker-compose'
      - 'go'
      - 'jq'
      - 'nmap'
      - 'packer'
      - 'python@2'
      - 'python@3'
      - 'ssh-copy-id'
      - 'tmux'
      - 'tree'
      - 'vault'
      - 'wget'
  tasks:
    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ brew_packages }}'

    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ brew_cask_packages }}'
