---
- name: Install macOS Software
  hosts: localhost
  connection: local
  vars:
    brew_cask_packages:
      # Tools/Admin
      - 'dbeaver-community'
      - 'docker-desktop'
      - 'leapp'
      - 'postman'

      # Browsers
      - 'firefox'
      - 'google-chrome'

      # AI Editors
      - 'trae'
      - 'windsurf'
      - 'antigravity'

      # Editors
      - 'jetbrains-toolbox'
      - 'visual-studio-code'
  
      # Virtual Machines 
      # - 'vagrant'
      # - 'virtualbox'
      # - 'virtualbox-extension-pack'

      # Office
      - 'microsoft-office'

      # Terminal
      - kitty

    brew_packages:
      # Tools/Admin
      - 'autoconf'
      - 'ansible'
      - 'bash-completion'
      - 'go'
      - 'jq'
      - 'nmap'
      - 'ssh-copy-id'
      - 'tree'
      - 'openfortivpn'
      - 'awscli'
      - 'pgcli'
      - 'mycli'
      - 'terraform'
      - 'terragrunt'
      - 'pocketbase'

      # Runtime Managers
      - 'uv'
      - 'nvm'
      - 'jenv'

      # pde
      - 'neovim'

  tasks:
    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ brew_packages }}'

    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: '{{ brew_cask_packages }}'
